package Panel;
import Form.FormMenuUtama;
import Panel.PanelTransaksiJual;
import javax.swing.JFrame;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.util.UIScale;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import kasir.main.Main;
/**
 *
 * @author USER
 */
public class PanelLogin extends javax.swing.JPanel {

    private String activeUserId;
    public PanelLogin() {
        initComponents();
        
        
        
        TxUsername.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "username anda");
        TxPassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "password anda");
        lb_hide.setVisible(false);
        
      
    }
    public enum LevelUser {
    admin,
    user
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pn_login1 = new javax.swing.JPanel();
        lb_show = new javax.swing.JLabel();
        lb_hide = new javax.swing.JLabel();
        TxUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxPassword = new javax.swing.JPasswordField();
        tx_login = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        Pn_login2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();

        Pn_login1.setBackground(new java.awt.Color(255, 255, 255));
        Pn_login1.setMinimumSize(new java.awt.Dimension(475, 600));
        Pn_login1.setPreferredSize(new java.awt.Dimension(475, 600));
        Pn_login1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/eye_5758547 (1).png"))); // NOI18N
        lb_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_showMouseClicked(evt);
            }
        });
        Pn_login1.add(lb_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 60, 60));

        lb_hide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hidden_5758686 (1).png"))); // NOI18N
        lb_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hideMouseClicked(evt);
            }
        });
        Pn_login1.add(lb_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 60, 60));

        TxUsername.setPreferredSize(new java.awt.Dimension(70, 23));
        TxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxUsernameActionPerformed(evt);
            }
        });
        Pn_login1.add(TxUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 350, 60));

        jLabel1.setText("Username");
        Pn_login1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 20));
        Pn_login1.add(TxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 350, 60));

        tx_login.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tx_login.setText("Login");
        Pn_login1.add(tx_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, 70));

        jLabel3.setText("Password");
        Pn_login1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 220, 20));

        btLogin.setBackground(new java.awt.Color(51, 51, 51));
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("LOGIN");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        Pn_login1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 300, 50));

        Pn_login2.setBackground(new java.awt.Color(28, 69, 50));
        Pn_login2.setForeground(new java.awt.Color(28, 69, 50));
        Pn_login2.setMinimumSize(new java.awt.Dimension(475, 600));
        Pn_login2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lorem ipsum bla ble blo haha anjay mabar");
        Pn_login2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        btRegister.setBackground(new java.awt.Color(51, 51, 51));
        btRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btRegister.setForeground(new java.awt.Color(255, 255, 255));
        btRegister.setText("Register");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });
        Pn_login2.add(btRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 450, 242, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pn_login1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pn_login2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pn_login1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pn_login2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_showMouseClicked
        lb_show.setVisible(false);
        lb_hide.setVisible(true);
        TxPassword.setEchoChar((char)0);
    }//GEN-LAST:event_lb_showMouseClicked

    private void lb_hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hideMouseClicked
        lb_show.setVisible(true);
        lb_hide.setVisible(false);
        TxPassword.setEchoChar('*');
    }//GEN-LAST:event_lb_hideMouseClicked

    private void TxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxUsernameActionPerformed
public class UserSession {
    private static String username;
    private static String namaKasir; // tambahkan ini kalau belum ada

    public static void setUsername(String user) {
        username = user;
    }

    public static String getUsername() {
        return username;
    }

    public static void setNamaKasir(String nama) {
        namaKasir = nama;
    }

    public static String getNamaKasir() {
        return namaKasir;
    }
}

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        String User, Pw, query, passDB;
String SUrl, SUser, SPass;
PanelLogin.LevelUser level = null;

SUrl = "jdbc:mysql://localhost:3306/koperasi_nuris";
SUser = "root";
SPass = "";

User = TxUsername.getText();
Pw = TxPassword.getText();

if ("".equals(User)) {
    JOptionPane.showMessageDialog(new JFrame(), "Username harus di isi", "Error", JOptionPane.ERROR_MESSAGE);
    return;
} else if ("".equals(Pw)) {
    JOptionPane.showMessageDialog(new JFrame(), "Password harus di isi", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    java.sql.Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
    query = "SELECT * FROM user WHERE Username = ?";

    PreparedStatement s = con.prepareStatement(query);
    s.setString(1, User);
    ResultSet rs = s.executeQuery();

    if (rs.next()) {
        passDB = rs.getString("Password");
        String levelStr = rs.getString("Level");
        String nama = rs.getString("NamaUser");
        UserSession.setNamaKasir(nama); // ini yang dibutuhkan panel transaksi


        if (levelStr == null) {
            JOptionPane.showMessageDialog(new JFrame(), "Level kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Penyesuaian dengan enum Java
        if (levelStr.equalsIgnoreCase("admin")) {
            level = PanelLogin.LevelUser.admin;
        } else if (levelStr.equalsIgnoreCase("user")) {
            level = PanelLogin.LevelUser.user;
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Level tidak dikenali: " + levelStr, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Pw.equals(passDB)) {
            // Menyimpan ID pengguna yang aktif setelah login
            activeUserId = rs.getString("IDUser");
            

            System.out.println("ID Pengguna yang aktif: " + activeUserId);

            if (level == PanelLogin.LevelUser.admin) {
                System.out.println("Login sebagai Admin");
                System.out.println("Nama kasir diset: " + nama);
                UserSession.setNamaKasir(rs.getString("NamaUser"));
                UserSession.setNamaKasir(nama); // ini yang dibutuhkan panel transaksi

                FormMenuUtama.login();
                
            } else if (level == PanelLogin.LevelUser.user) {
                System.out.println("Login sebagai User");
                FormMenuUtama.login();    
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Username atau Password salah", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(new JFrame(), "User tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
    }

    con.close();
    TxPassword.setText("");
    TxUsername.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(new JFrame(), "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btLoginActionPerformed



    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        FormMenuUtama.showRegister();
    }//GEN-LAST:event_btRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pn_login1;
    private javax.swing.JPanel Pn_login2;
    private javax.swing.JPasswordField TxPassword;
    private javax.swing.JTextField TxUsername;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_hide;
    private javax.swing.JLabel lb_show;
    private javax.swing.JLabel tx_login;
    // End of variables declaration//GEN-END:variables
        
    
}

