/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;
import Panel.PopupTambahStok;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Window;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.TableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author ASUS Vivobook
 */
public class stok extends javax.swing.JPanel {

    /**
     * Creates new form stok
     */
    public stok() {
        initComponents();
        tampilDatastok();
    }
    
    private void bukaPopupTambahStok() {
    int selectedRow = tabel_stok.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit terlebih dahulu!");
        return;
    }
    
    // Ambil data dari baris yang dipilih
    Map<String, String> stokData = new HashMap<>();
    stokData.put("NamaBarang", tabel_stok.getValueAt(selectedRow, 0).toString());
    stokData.put("JumlahMasuk", tabel_stok.getValueAt(selectedRow, 1).toString());
    stokData.put("JumlahKeluar", tabel_stok.getValueAt(selectedRow, 2).toString());
    stokData.put("TanggalUpdate", tabel_stok.getValueAt(selectedRow, 3).toString());
    stokData.put("TanggalKadaluarsa", tabel_stok.getValueAt(selectedRow, 4).toString());
    stokData.put("Kategori", tabel_stok.getValueAt(selectedRow, 5).toString());
    
    // Buka popup edit dengan data yang dipilih
    bukaPopupEditStok(stokData);
}
    
    private void bukaPopupEditStok(Map<String, String> stokData) {
    PopupTambahStok panel = new PopupTambahStok(stokData);
    
    // Set listener untuk refresh tabel setelah edit
    panel.setDataSavedListener(() -> {
        tampilDatastok();
    });

    JDialog dialog = new JDialog((JFrame) null, "Edit Stok", true);
    dialog.getContentPane().add(panel);
    dialog.pack();
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true);
}

    
    public void tampilDatastok() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nama Barang");
    model.addColumn("Jumlah Masuk");
    model.addColumn("Jumlah Keluar");
    model.addColumn("Tanggal Update");
    model.addColumn("Kadaluarsa");
    model.addColumn("Kategori");
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    try {
        
        // Ganti sesuai koneksi database kamu
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi_nuris", "root", "");
        Statement stmt = conn.createStatement();
        // Menggabungkan tabel stok dan barang berdasarkan IDBarang
        String sql = "SELECT b.NamaBarang, s.JumlahMasuk, s.JumlahKeluar, s.TanggalUpdate, s.TanggalKadaluarsa, k.NamaKategori " +
                     "FROM barang b " +
                     "JOIN stok s ON s.IDBarang = b.IDBarang JOIN kategori k ON k.IDKategori = b.IDKategori";
        ResultSet rs = stmt.executeQuery(sql);

while (rs.next()) {
    String tanggalUpdate = "";
    String tanggalKadaluarsa = "";

    Date tglUpdate = rs.getDate("TanggalUpdate");
    if (tglUpdate != null) {
        tanggalUpdate = sdf.format(tglUpdate);
    }

    Date tglKadaluarsa = rs.getDate("TanggalKadaluarsa");
    if (tglKadaluarsa != null) {
        tanggalKadaluarsa = sdf.format(tglKadaluarsa);
    }

    model.addRow(new Object[]{
        rs.getString("NamaBarang"),
        rs.getInt("JumlahMasuk"),
        rs.getInt("JumlahKeluar"),
        tanggalUpdate,
        tanggalKadaluarsa,
        rs.getString("NamaKategori"),
    });
}

        tabel_stok.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_stok = new javax.swing.JTable();
        Edit = new javax.swing.JButton();

        jLabel1.setText("STOK");

        tabel_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Jumlah Masuk", "Jumlah Keluar", "Tanggal Update", "Kadaluarsa"
            }
        ));
        jScrollPane1.setViewportView(tabel_stok);

        Edit.setBackground(new java.awt.Color(0, 153, 0));
        Edit.setText("Edit ");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Edit)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Edit)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
    bukaPopupTambahStok();
    
    }//GEN-LAST:event_EditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_stok;
    // End of variables declaration//GEN-END:variables
}
