/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Window;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author ASUS Vivobook
 */
public class stok extends javax.swing.JPanel {

    /**
     * Creates new form stok
     */
    public stok() {
        initComponents();
        tampilDatastok();
    }
    
    private void bukaPopupTambahStok() {
    int selectedRow = tabel_stok.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan diedit terlebih dahulu!");
        return;
    }
    
    // Ambil data dari baris yang dipilih
    Map<String, String> stokData = new HashMap<>();
    stokData.put("IDBarang", tabel_stok.getValueAt(selectedRow, 0).toString());
    stokData.put("NamaBarang", tabel_stok.getValueAt(selectedRow, 1).toString());
    stokData.put("JumlahMasuk", tabel_stok.getValueAt(selectedRow, 2).toString());
    stokData.put("JumlahKeluar", tabel_stok.getValueAt(selectedRow, 3).toString());
    stokData.put("TanggalUpdate", tabel_stok.getValueAt(selectedRow, 4).toString());
    stokData.put("TanggalKadaluarsa", tabel_stok.getValueAt(selectedRow, 5).toString());
    
    // Buka popup edit dengan data yang dipilih
    bukaPopupEditStok(stokData);
}
    
    private void bukaPopupEditStok(Map<String, String> stokData) {
    PopupTambahStok panel = new PopupTambahStok(stokData);
    
    // Set listener untuk refresh tabel setelah edit
    panel.setDataSavedListener(() -> {
        tampilDatastok();
    });

    JDialog dialog = new JDialog((JFrame) null, "Edit Stok", true);
    dialog.getContentPane().add(panel);
    dialog.pack();
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true);
}

    
    public void tampilDatastok() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Barang"); 
    model.addColumn("Nama Barang");
    model.addColumn("Jumlah Masuk");
    model.addColumn("Jumlah Keluar");
    model.addColumn("Tanggal Update");
    model.addColumn("Kadaluarsa");

    try {
        // Ganti sesuai koneksi database kamu
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/koperasi_nuris", "root", "");
        Statement stmt = conn.createStatement();
        // Menggabungkan tabel stok dan barang berdasarkan IDBarang
        String sql = "SELECT s.IDBarang, b.NamaBarang, s.JumlahMasuk, s.JumlahKeluar, s.TanggalUpdate, s.TanggalKadaluarsa " +
                     "FROM stok s " +
                     "JOIN barang b ON s.IDBarang = b.IDBarang";
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("IDBarang"),
                rs.getString("NamaBarang"),
                rs.getInt("JumlahMasuk"),
                rs.getInt("JumlahKeluar"),
                rs.getDate("TanggalUpdate"),
                rs.getDate("TanggalKadaluarsa")
            });
        }

        tabel_stok.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_stok = new javax.swing.JTable();
        Edit = new javax.swing.JButton();

        tabel_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Jumlah Masuk", "Jumlah Keluar", "Tanggal Update", "Kadaluarsa"
            }
        ));
        jScrollPane1.setViewportView(tabel_stok);

        Edit.setBackground(new java.awt.Color(0, 153, 0));
        Edit.setText("Edit ");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Edit)
                .addGap(123, 123, 123))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
    bukaPopupTambahStok();
    
    }//GEN-LAST:event_EditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_stok;
    // End of variables declaration//GEN-END:variables
}
